#!/bin/bash

sudo echo
clear

# Check arch linux news before updating
# cat /var/log/pacman.log | grep '\[PACMAN\] starting full system upgrade' | tail -n 3
# echo
# echo 'Listed above was the last system update date'
# read -p 'press any key to check arch linux news'
# lynx -cmd_script=search_news_list.lynx https://archlinux.org/news/
newsboat --url-file=${HOME}/.newsboat/urls --refresh-on-start

sudo reflector --verbose --country Taiwan  \
			   --age 12 --protocol https   \
			   --sort rate --number 5      \
			   --save /etc/pacman.d/mirrorlist
time sudo pacman -Syu --noconfirm --verbose
paccache --remove \
         --cachedir /var/cache/pacman/pkg --keep 1
